package view;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import common.DummyData;
import model.Attendance;
import model.User;

import java.util.List;
import java.util.stream.Collectors;

/**
 * @author User
 */
public class attendance extends javax.swing.JPanel {

    private DummyData dummyData;
    private User user;

    /**
     * Creates new form DB
     */
    public attendance(DummyData dummyData, User user) {
        this.dummyData = dummyData;
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        List<Attendance> attendances = dummyData.getAttendances().stream().filter(x -> x.getGradeInfo().getStudent() == user).collect(Collectors.toList());

        Object[][] data = new Object[attendances.size()][2];

        int index = 0;
        for (Attendance attendance : attendances) {
            data[index][0] = attendance.getGradeInfo().getSubject().getName();
            data[index][1] = attendance.getTime();
            index++;
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
               data,
                new String[]{
                        "과목명", "출석일자"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
